name: 'Regular test of Dapps Website'

on:
  schedule:
    - cron: '0 0 * * *'

  pull_request:
    branches: ['main']

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v2

      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # pin@v3.8.1
        with:
          node-version: 18.16

      - name: Setup cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # pin@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-npm-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v1-
        continue-on-error: true

      - name: Install dependencies
        run: npm install

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run e2e tests (headful)
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
          npm run synpress:run-prod
        env:
          DISPLAY: :0.0

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v2
        if: always()
        with:
          name: dapps-video
          path: |
            tests/e2e/videos
        continue-on-error: true
